### ISSUE TITLE
作者你好,是否经过商业使用验证?

### ISSUE THREAD

**Issue by feng99** [bullsoft/phalconplus#9]
作者你好,是否经过商业使用验证?
是否有压测数据?
对PHP版本是否有明确要求?
最新版本是基于phalcon哪个版本封装的?
建议补充下最新版本的改动说明

**Comment by feng99** [comment]
已贡献star

**Comment by guweigang** [comment]
Readme里面有说明哦
*  PHP 7.0 or above
* cPhalcon 3.4.x - https://github.com/phalcon/cphalcon/tree/3.4.x

压测做过没披露数据，扩展级的框架封装性能不会差。
未经过大型商业验证，可以从小规模的做起。
感谢star

**Comment by feng99** [comment]
谢谢  了解了.


演示
Frontend: http://demo.phalconphp.org
Backend: http://server.phalconphp.org

这两个地址都打不开了

**Comment by feng99** [comment]
我最疑惑的还是  yar rpc
这个你在生产环境用过吗  有问题吗?
特别是跨项目调用的时候

**Comment by guweigang** [comment]
yar rpc我在生产用过，没问题。
不过为了解除对yar的依赖我自己又封装了个简单的adapter

另外，phalconphp.org 域名我早就停用了，新的演示可以看这个：
https://centcms.bullsoft.org/

**Comment by feng99** [comment]
> yar rpc我在生产用过，没问题。
> 不过为了解除对yar的依赖我自己又封装了个简单的adapter，如果在config中配置了
> 
> ```
> application.handler = "yar"
> ```
> 
> 就会使用yar作为RPC的handler，如果不配置则会使用一个非常简单的handler:
> 
> https://github.com/bullsoft/phalconplus/blob/master/phalconplus/RPC/Yar.zep#L40
> 
> 另外，phalconphp.org 域名我早就停用了，新的演示可以看这个：
> https://centcms.bullsoft.org/

这个演示  注册后登录看到的是一个CMS系统.


另外跨项目调用   那个mysql的事务嵌套问题,您是怎么解决的.

**Comment by guweigang** [comment]
是的，演示背后是三套服务
- OAuth服务，
- cms Web mode
- cms Srv mode

你讲的事务嵌套是什么意思？
1. RPC Client调用Server，Client有事务，调用的Server有事务？
    请参考柔性事务解决方案，采用谁发起谁负责的原则，Client负责搞定本地事务，异步Rpc调用Server
2. 同一个进程内事务嵌套？
     - 如果在Phalcon中是同一个db service，那Phalcon帮你解决了嵌套问题，最外层的事务是真正有效的事务
     -  如果是不同的db service，请改成同一个db service

**Comment by feng99** [comment]
嗯 我想明白了  既然服务都拆开了 
那clent处理好自己的事务    server也处理好自己的事务    就可以了

关于跨库事务  
数据库在同一个物理机器 
同一个实例 
同一个端口下 
虽然我创建了N个db,
在一个进程里   同时更新N个库,是不是没有 跨库事务的问题? 

还是说  只要不是同一个DB,(即使同一个物理机,同一个3306端口)  就会有跨库事务问题?

**Comment by guweigang** [comment]
一个DB，不同的逻辑库，不会有跨库事务。
如果要在Phalcon中使用，记得override  `Phalcon\Mvc\Model:: getSchema`

**Comment by guweigang** [comment]
没其他问题我关了啊

**Comment by feng99** [comment]
好的，谢谢指点。
